# This rule is not used by the project metallb-neutron-sync itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to openstack.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: metallb-neutron-sync
    app.kubernetes.io/managed-by: kustomize
  name: openstackloadbalanceservice-viewer-role
rules:
- apiGroups:
  - openstack.example.com
  resources:
  - openstackloadbalanceservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.example.com
  resources:
  - openstackloadbalanceservices/status
  verbs:
  - get
